#!/bin/sh
# todo: handle interop between floating and tiled better
# https://github.com/neeasade/dotfiles/blob/master/wm/.wm/scripts/interact/focus.sh

dir="$1"

bspc config pointer_follows_monitor true
#bspc config pointer_follows_focus true

if bspc query -N -n .focused.local.fullscreen; then
    bspc monitor -f "$dir"
    exit
fi

[ "$(bspc query -N -n .focused.local.floating)" ] && state='floating' || state='!floating'

if ! bspc node -f "$dir".local."$state"; then
    bspc config focus_follows_pointer false
    bspc monitor -f "$dir"
    bspc config focus_follows_pointer true
fi

bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false


