#!/bin/sh

DIALOG_RESULT=$(echo 'lock\nshutdown\nreboot' | rofi -dmenu -i -p "[ Computer ] : " -hide-scrollbar -tokenize -lines 4 -eh 1 -width 40 -location 8 -xoffset 170 -yoffset 70 -padding 30 -disable-history -font "RobotoMono 18")

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "lock" ];
then
    exec lock
elif [ "$DIALOG_RESULT" = "shutdown" ];
then
    exec sudo shutdown -P now
elif [ "$DIALOG_RESULT" = "reboot" ];
then
    exec sudo reboot
fi
