#!/bin/sh
#compare packages

p1_xq="$(xbps-query -R "$1")"
p2_xq="$(xbps-query -R "$2")"

if [ -z "$p1_xq" ]; then
	echo wrong package name "$1"
	exit 1
elif [ -z "$p2_xq" ]; then
        echo wrong package name "$2"
        exit 1
fi

p1_d="$(xbps-query --fulldeptree -Rx "$1" | wc -l)"
p2_d="$(xbps-query --fulldeptree -Rx "$2" | wc -l)"

p1_s="$(xbps-query -R "$1" | grep installed_size | awk '{print $2}')"
p2_s="$(xbps-query -R "$2" | grep installed_size | awk '{print $2}')"

p1_l="$(xbps-query -R "$1" | grep license | awk '{print $2}')"
p2_l="$(xbps-query -R "$2" | grep license | awk '{print $2}')"

#echo "\033[1mpackage name:\033[0m "$1" vs "$2""
echo "dependencies:   "$p1_d"       "$p2_d""
echo "installed_size: "$p1_s"    "$p2_s""
echo "license:        "$p1_l"     "$p2_l""
 